version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:latest

jobs:
  build-frontend:
    executor: node
    working_directory: ~/moksha/frontend
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths: ./node_modules
      - run: npm test
  build-backend:
    executor: node
    working_directory: ~/moksha/backend
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths: ./node_modules
      - run: npm test

workflows:
  version: 2.1
  build-app:
    jobs:
      - build-frontend
      - build-backend
